spring.datasource.url=jdbc:mysql://crud-db.clcwkga62h5n.ap-south-1.rds.amazonaws.com:3306/employee_management_system?useSSL=false
spring.datasource.username=admin
spring.datasource.password=dNANI0121

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto = update
