spring.datasource.url=jdbc:mysql://crud-project.clcwkga62h5n.ap-south-1.rds.amazonaws.com:3306/CRUD_db2?useSSL=false
spring.datasource.username=admin
spring.datasource.password=Nani0121

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto = update
